import Image from 'next/image';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import TopAnime from '@/components/views/anime/TopAnime';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className={`flex min-h-screen flex-col items-center justify-between px-28 py-6 ${inter.className}`}>
        <TopAnime headerTitle="TERPOPULER" linkShowAll="/top/anime" query="limit=5" />
        <div className="flex justify-between w-full mt-6">
          <div className="w-[62%]">
            <TopAnime headerTitle="SEDANG TAYANG" linkShowAll="/top/anime" query="limit=3" />
          </div>
          <div className="w-[36%]">
            <TopAnime headerTitle="REKOMENDASI" linkShowAll="/top/anime" query="limit=1" className="w-[23rem]" styleTitle="absolute bottom-4 w-full" />
          </div>
        </div>
      </main>
    </>
  );
}
